FEAT: Update object state for `print_tree()
ansys/pymechanical pull request #1005
Opened 2024-12-17 15:48 UTC by dipinknair

update object state of each object in tree

app.print_tree()
```
├── Project
|  ├── Model
|  |  ├── Geometry Imports (✓)
|  |  |  ├── Geometry Import (✓)
|  |  ├── Geometry (✓)
|  |  |  ├── Solid Bodies
|  |  |  |  ├── Solid
|  |  ├── Materials (✓)
|  |  |  ├── Elastomer Sample (Yeoh ) (✓)
|  |  |  ├── Structural Steel (✓)
|  |  ├── Coordinate Systems (✓)
|  |  |  ├── Global Coordinate System (✓)
|  |  ├── Remote Points (✓)
|  |  ├── Connections (✓)
|  |  |  ├── Contacts (✓)
|  |  |  |  ├── Frictional - Solid To Solid (✓)
|  |  ├── Mesh (✓)
|  |  |  ├── Patch Conforming Method (✓)
|  |  |  ├── Body Sizing (✓)
|  |  ├── Static Structural (⚡︎)
|  |  |  ├── Analysis Settings (✓)
|  |  |  ├── Fixed Support (✓)
|  |  |  ├── Displacement (✓)
|  |  |  ├── Frictionless Support (✓)
|  |  |  ├── Commands (APDL) (✓)
|  |  |  ├── Nonlinear Adaptive Region (✓)
|  |  |  ├── Solution (⚡︎)
|  |  |  |  ├── Solution Information (⚡︎)
|  |  |  |  ├── Total Deformation (⚡︎)
|  |  |  |  ├── Equivalent Total Strain (⚡︎)
|  |  |  |  ├── Commands (APDL) (⚡︎)
|  |  |  |  |  ├── Post Output
|  |  |  |  ├── MESH_SKEWNESS (⚡︎)
|  |  |  |  ├── MESH_JACOBIAN_RATIO_MAPDL (⚡︎)
```

2024-12-17 15:56 UTC, RobPasMue commented on src/ansys/mechanical/core/embedding/app.py
> +                node_name += " (✕)"
Are these characters utf8 compatible?... I doubt it.

2024-12-17 15:56 UTC, RobPasMue requested changes

2024-12-17 15:56 UTC, RobPasMue commented on src/ansys/mechanical/core/embedding/app.py
> +                node_name += " (✕)"
It might fail in many machines/environments

2024-12-20 19:45 UTC, dipinknair commented
pinging @koubaa for final approval in relation to Mechanical object state

2024-12-20 21:38 UTC, koubaa approved these changes

2024-12-20 21:38 UTC, merged