Add LS Dyna unit test
ansys/pymechanical pull request #584
Opened 2024-02-05 15:25 UTC by dipinknair

Simple unit test to check LS Dyna system in Mechanical
 Closes #581

2024-02-05 16:31 UTC, sbradrick approved these changes

2024-02-07 13:30 UTC, koubaa commented on .codespellrc
> +ignore-words-list = ans, globaly
this is a typo

2024-02-07 13:32 UTC, koubaa commented on tests/embedding/test_qk_eng_wb2.py
> +@pytest.mark.embedding
put this in another file, not `test_qk_eng_wb2.py`.  This file is intended to contain the port of some QA tests to pymechanical.

2024-02-07 13:33 UTC, koubaa commented on tests/embedding/test_qk_eng_wb2.py
> +@pytest.mark.minimum_version(241)
this needs to be marked as windows only, we have a limitation for LSDYNA on linux embedding right now

2024-02-07 13:34 UTC, koubaa requested changes
see my comments

2024-02-07 20:01 UTC, dipinknair commented on .codespellrc
> +ignore-words-list = ans, globaly
This is to ignore `GlobalY` in test

2024-02-09 13:03 UTC, koubaa commented on tests/embedding/test_analysis.py
> +# Copyright (C) 2022 - 2024 ANSYS, Inc. and/or its affiliates.
I think a better name for this file is test_dyna.py

2024-02-09 13:03 UTC, koubaa commented on tests/embedding/test_analysis.py
> +def test_lsdyna(printer, selection, embedded_app):
let's be more specific about the type of the test. How would you describe it?

2024-02-09 13:04 UTC, koubaa approved these changes

2024-02-09 13:04 UTC, koubaa commented on tests/embedding/test_qk_eng_wb2.py
> +    globals().update(global_variables(embedded_app, True))
if True is used here, I would expect to see shortened namespaces elsewhere

2024-02-20 13:05 UTC, koubaa approved these changes

2024-03-07 17:13 UTC, sbradrick approved these changes

2024-03-11 19:06 UTC, merged

2024-03-14 14:06 UTC, sbradrick commented on tests/embedding/test_dyna.py
> +    """
This test focuses on a LSDyna analysis in Mechanical for the Windows environment only. This test involves a simple geometry with high velocity striking a rigid wall.