FEAT: Integrate ansys visualization tool
ansys/pymechanical pull request #797
Opened 2024-06-28 03:14 UTC by dipinknair

- Replace pyvista plotter with ansys visualization plotter
 - add func to return plotter object.

2024-06-28 13:58 UTC, RobPasMue commented on pyproject.toml
> +    "ansys-tools-visualization-interface==0.2.6",
I wouldn't hardcode a specific version - just use above this one

2024-07-01 09:10 UTC, AlejandroFernandezLuces requested changes
Thanks for the integration of the visualization interface 🙂 

A couple of comments, I see this is still in draft, feel free to ping me again when needed.

2024-07-01 09:10 UTC, AlejandroFernandezLuces commented on src/ansys/mechanical/core/embedding/viz/pyvista_plotter.py
>  def to_pyvista_plotter(app: "ansys.mechanical.core.embedding.App"):
This function should be renamed, since we are not using `pyvista`.

2024-07-01 09:10 UTC, AlejandroFernandezLuces commented on src/ansys/mechanical/core/embedding/viz/pyvista_plotter.py
>          plotter.add_mesh(polydata, color=color, smooth_shading=True)
You probably want to use `plot` method here, extra kwargs are passed downstream to the PyVista backend.
```suggestion
        plotter.plot(polydata, color=color, smooth_shading=True)
```

2024-07-31 14:47 UTC, closed without merging