FIX: Throw value error for unsupported version of Mechanical
ansys/pymechanical pull request #917
Opened 2024-09-23 20:26 UTC by dipinknair

Fixed #913

2024-09-24 13:06 UTC, koubaa commented on src/ansys/mechanical/core/embedding/initializer.py
> +    elif version not in SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS_WINDOWS:
what about 251?

2024-09-26 14:12 UTC, koubaa commented on src/ansys/mechanical/core/embedding/initializer.py
> +    elif version < next(iter(SUPPORTED_MECHANICAL_EMBEDDING_VERSIONS_WINDOWS)):
minor - "WINDOWS" in this variable name is unnecessary

2024-09-26 14:13 UTC, koubaa requested changes

2024-09-26 14:23 UTC, dipinknair commented on src/ansys/mechanical/core/embedding/initializer.py
> +    if is_old_version is not None and is_old_version == "1" and version >= 231:
there is no support for version less than 231 right ?

2024-09-26 14:57 UTC, dipinknair commented on src/ansys/mechanical/core/embedding/resolver.py
> +    if version == 231:  # pragma: no cover
Yes

2024-09-27 15:45 UTC, dipinknair commented on src/ansys/mechanical/core/embedding/resolver.py
> +    if version == 231:  # pragma: no cover
This will removed as per our discussion.

2024-09-27 18:42 UTC, koubaa approved these changes

2024-09-30 13:55 UTC, merged