doc: add Mechanical API link to Mechanical Scripting page
ansys/pymechanical pull request #972
Opened 2024-11-06 16:51 UTC by klmcadams

2024-11-07 07:53 UTC, RobPasMue requested changes

2024-11-07 07:53 UTC, RobPasMue commented on doc/source/user_guide_scripting/index.rst
> +and the `Scripting in Mechanical Guide`_ in the Ansys Help portal.
This should be added with a ``.. note::`` so that users pay attention to it.

2024-11-13 20:09 UTC, RobPasMue commented
@klmcadams - what's the status here?

2024-11-14 15:31 UTC, RobPasMue approved these changes

2024-11-14 15:56 UTC, klmcadams commented
@RobPasMue does this look okay?

![note](https://github.com/user-attachments/assets/69c12c46-0694-481b-bbdc-d37f66979ad8)

2024-11-14 16:10 UTC, merged

2024-11-15 06:51 UTC, RobPasMue commented
Works for me - thanks @klmcadams!